-- =============================================================
-- ZEUSSHOP — Supabase Database Setup
-- -------------------------------------------------------------
-- Run this file in: Supabase Dashboard → SQL Editor → Run (all)
-- AFTER you create your project and an admin Auth user.
--
-- Then enable the tables for Realtime (last section) if you want
-- the shop to update live when the admin adds/changes skins.
-- =============================================================

-- -------------------------------------------------------------
-- 1) TABLES
-- -------------------------------------------------------------
create table if not exists public.skins (
  id bigint generated by default as identity primary key,
  name text not null unique,
  img text not null default '',
  weapon text not null default 'Rifle',
  wear text not null default 'Factory New',
  rarity text not null default 'Covert',
  type text not null default 'Normal',
  price numeric(12,2) not null default 0,
  discount int not null default 0,
  sort int not null default 0,
  delivery_mode text not null default 'immediate',
  delivery_days int not null default 0,
  created_at timestamptz not null default now()
);
alter table public.skins add column if not exists delivery_mode text not null default 'immediate';
alter table public.skins add column if not exists delivery_days int not null default 0;

create table if not exists public.orders (
  id bigint primary key,
  telegram text not null,
  items jsonb not null default '[]',
  total numeric(12,2) not null default 0,
  status text not null default 'pending',
  coupon text not null default '',
  date timestamptz not null default now()
);
alter table public.orders add column if not exists coupon text not null default '';
create index if not exists idx_orders_coupon on public.orders (coupon);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  telegram text not null,
  name text not null,
  price numeric(12,2) not null default 0,
  img text not null default '',
  weapon text not null default '',
  wear text not null default '',
  rarity text not null default '',
  type text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists idx_inv_tg on public.inventory (telegram);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  tg text not null unique,
  date timestamptz not null default now()
);

create table if not exists public.announcement (
  id int primary key default 1,
  enabled boolean not null default false,
  text text not null default '',
  constraint announcement_singleton check (id = 1)
);
insert into public.announcement (id, enabled, text)
values (1, false, '')
on conflict (id) do nothing;

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

-- Admins = the Auth users allowed to manage the panel.
-- (RLS policies below refuse writes to anyone NOT in this table.)
create table if not exists public.admins (
  id uuid primary key references auth.users (id) on delete cascade
);

-- -------------------------------------------------------------
-- 2) ROW LEVEL SECURITY
-- -------------------------------------------------------------
do $$
begin
  execute 'alter table public.skins enable row level security';
  execute 'alter table public.orders enable row level security';
  execute 'alter table public.inventory enable row level security';
  execute 'alter table public.users enable row level security';
  execute 'alter table public.announcement enable row level security';
  execute 'alter table public.admins enable row level security';
  execute 'alter table public.site_settings enable row level security';
end $$;

drop policy if exists "skins public read"          on public.skins;
drop policy if exists "skins admin write"          on public.skins;
drop policy if exists "orders admin read"          on public.orders;
drop policy if exists "orders public read approved" on public.orders;
drop policy if exists "orders public insert"       on public.orders;
drop policy if exists "orders admin change"        on public.orders;
drop policy if exists "orders admin delete"        on public.orders;
drop policy if exists "inventory public read"      on public.inventory;
drop policy if exists "inventory admin write"      on public.inventory;
drop policy if exists "users public insert"        on public.users;
drop policy if exists "users admin read"           on public.users;
drop policy if exists "users admin change"         on public.users;
drop policy if exists "announcement public read"   on public.announcement;
drop policy if exists "announcement admin write"   on public.announcement;
drop policy if exists "admins read own"            on public.admins;
drop policy if exists "settings public read"       on public.site_settings;
drop policy if exists "settings admin write"       on public.site_settings;

-- helper: is the current session an admin?
create or replace function public.is_admin()
returns boolean language sql stable security definer as $$
  select exists (select 1 from public.admins where id = auth.uid())
$$;

-- skins: anyone can view, only admins add/change/delete
create policy "skins public read" on public.skins
  for select using (true);
create policy "skins admin write" on public.skins
  for all using (public.is_admin()) with check (public.is_admin());

-- orders: everyone can place, only admins read/approve/reject, public sees approved
create policy "orders public insert" on public.orders
  for insert with check (true);
create policy "orders public read approved" on public.orders
  for select using (status = 'approved');
create policy "orders admin read" on public.orders
  for select using (public.is_admin());
create policy "orders admin change" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());
create policy "orders admin delete" on public.orders
  for delete using (public.is_admin());

-- inventory: viewable publicly (by telegram), only admins add
create policy "inventory public read" on public.inventory
  for select using (true);
create policy "inventory admin write" on public.inventory
  for all using (public.is_admin()) with check (public.is_admin());

-- users: registration is public, list is admin-only
create policy "users public insert" on public.users
  for insert with check (true);
create policy "users admin read" on public.users
  for select using (public.is_admin());
create policy "users admin change" on public.users
  for update using (public.is_admin()) with check (public.is_admin());
create policy "users admin delete" on public.users
  for delete using (public.is_admin());

-- default payment card shown at checkout (admin can change from the panel)
insert into public.site_settings (key, value) values
  ('pay_card', '6037-9919-7890-0000'),
  ('pay_card_name', 'علی رضایی')
on conflict (key) do nothing;

-- announcement: public read, admin update
create policy "announcement public read" on public.announcement
  for select using (true);
create policy "announcement admin write" on public.announcement
  for all using (public.is_admin()) with check (public.is_admin());

-- admins: only members can see the membership table
create policy "admins read own" on public.admins
  for select using (auth.uid() = id);

-- site settings: public read, admin update
create policy "settings public read" on public.site_settings
  for select using (true);
create policy "settings admin write" on public.site_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- -------------------------------------------------------------
-- 3) AFTER YOU CREATE THE ADMIN USER
--    (*) Authentication → Users → Add user (email + password)
--    Then run this (replace YOUR_ADMIN_EMAIL):
--        insert into public.admins (id)
--        select id from auth.users where email = 'YOUR_ADMIN_EMAIL'
--        on conflict do nothing;
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- 4) REALTIME (live updates for shop catalog, orders, users, inventory)
--    Idempotent: safe to re-run. Adds tables that are not published yet.
-- -------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'skins') then
    alter publication supabase_realtime add table public.skins;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'announcement') then
    alter publication supabase_realtime add table public.announcement;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'site_settings') then
    alter publication supabase_realtime add table public.site_settings;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'users') then
    alter publication supabase_realtime add table public.users;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'inventory') then
    alter publication supabase_realtime add table public.inventory;
  end if;
end $$;

-- -------------------------------------------------------------
-- 5) LIVE USER COUNT for the shop hero ("+N کاربران فعال")
--    Run this ONCE. The shop (anonymous client) cannot list the
--    users table (RLS hides it), so we expose a safe count.
-- -------------------------------------------------------------
create or replace function public.count_users()
returns bigint
language sql stable security definer as $$
  select count(*)::bigint from public.users
$$;
revoke execute on function public.count_users() from public, anon, authenticated;
grant execute on function public.count_users() to anon, authenticated;

-- -------------------------------------------------------------
-- 6) COUPON SINGLE-USE (+ایمن: کد تخفیف فقط یک‌بار، برای همه)
--    Anonymous shoppers INSERT their claimed code here; the PRIMARY KEY
--    on "coupon" makes the second claim fail — even while the order is
--    still pending (pending orders are hidden by RLS, so the orders table
--    alone can't stop double-use). Run this ONCE.
-- -------------------------------------------------------------
create table if not exists public.coupon_claims (
  coupon text primary key,
  telegram text not null default '',
  created_at timestamptz not null default now()
);
alter table public.coupon_claims enable row level security;

drop policy if exists "claims public insert" on public.coupon_claims;
drop policy if exists "claims public read"   on public.coupon_claims;
drop policy if exists "claims public delete" on public.coupon_claims;

create policy "claims public insert" on public.coupon_claims
  for insert with check (true);
create policy "claims public read" on public.coupon_claims
  for select using (true);
create policy "claims public delete" on public.coupon_claims
  for delete using (public.is_admin());

-- -------------------------------------------------------------
-- 7) REPAIR (order & users policies) + ANTI-SPAM
--    Run this if any of these happen:
--      • Admin approval shows "در دیتابیس ذخیره نشد"
--      • New orders don't reach the panel / "کاربران فعال" stays 0
--    It re-adds the missing coupon column + RLS policies (safe to re-run),
--    makes "id" a real primary key, and installs the anti-spam guard so a
--    buyer can't flood orders (max 3 pending, min 30s between orders).
-- -------------------------------------------------------------
alter table public.orders add column if not exists coupon text not null default '';

do $$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.orders'::regclass and contype = 'p') then
    execute 'alter table public.orders add primary key (id)';
  end if;
  if not exists (select 1 from pg_indexes where schemaname = 'public' and tablename = 'orders' and indexname = 'idx_orders_telegram') then
    execute 'create index idx_orders_telegram on public.orders (telegram)';
  end if;
  if not exists (select 1 from pg_indexes where schemaname = 'public' and tablename = 'orders' and indexname = 'idx_orders_status') then
    execute 'create index idx_orders_status on public.orders (status)';
  end if;
end $$;

-- re-create the ORDERS policies (guarded: never fails even if a leftover exists)
alter table public.orders enable row level security;
do $$
declare p text;
begin
  foreach p in array array['orders public insert','orders public insert guarded','orders public read approved','orders admin read','orders admin change','orders admin delete'] loop
    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'orders' and policyname = p) then
      execute format('drop policy %I on public.orders', p);
    end if;
  end loop;
end $$;

create policy "orders public read approved" on public.orders
  for select using (status = 'approved');
create policy "orders admin read" on public.orders
  for select using (public.is_admin());
create policy "orders admin change" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());
create policy "orders admin delete" on public.orders
  for delete using (public.is_admin());

-- anti-spam RPC: allowed = less than 3 pending orders AND last order older than 30s
create or replace function public.checkout_allowed(tg text)
returns boolean language sql stable security definer as $$
  select
    (select count(*) from public.orders where telegram = tg and status = 'pending') < 3
    and (select coalesce(max(date), '-infinity') from public.orders where telegram = tg)
        < now() - interval '30 seconds'
$$;
revoke execute on function public.checkout_allowed(text) from public, anon, authenticated;
grant execute on function public.checkout_allowed(text) to anon, authenticated;

-- orders may ONLY be inserted when the anti-spam check passes
create policy "orders public insert guarded" on public.orders
  for insert with check (public.checkout_allowed(telegram));

-- make sure USERS inserts still reach the DB (active-user counter)
alter table public.users enable row level security;
do $$
declare p text;
begin
  foreach p in array array['users public insert','users admin read','users admin change','users admin delete'] loop
    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = p) then
      execute format('drop policy %I on public.users', p);
    end if;
  end loop;
end $$;
create policy "users public insert" on public.users
  for insert with check (true);
create policy "users admin read" on public.users
  for select using (public.is_admin());
create policy "users admin change" on public.users
  for update using (public.is_admin()) with check (public.is_admin());
create policy "users admin delete" on public.users
  for delete using (public.is_admin());

-- default payment card shown at checkout (admin can change from the panel)
insert into public.site_settings (key, value) values
  ('pay_card', '6037-9919-7890-0000'),
  ('pay_card_name', 'علی رضایی')
on conflict (key) do nothing;